#!/bin/bash

#PBS -A TG-DMR110037

# specify job name 
#PBS -N helium_mpi

#PBS -o log
#PBS -l walltime=00:02:00,size=480

# specify number of procs

#PBS -j oe

cd $PBS_O_WORKDIR

echo 'Started at' $(date)
#echo 'Number of cores: ' $NSLOTS

#ulimit -s unlimited
#time mpirun -n $NSLOTS ./qm
aprun -n 480 ./qm
   
echo 'Ended at' $(date)
exit 
